### ISSUE TITLE
AttributeError: 'CelebAPrunedAligned_MAFLVal' object has no attribute 'use_ims'

### ISSUE THREAD

**Issue by schuhschuh** [jamt9000/DVE#2]
When trying to train a SmallNet on the `celeba` dataset using the configuration file http://www.robots.ox.ac.uk/~vgg/research/DVE/data/models/celeba-smallnet-3d-dve/2019-08-08_17-54-21/config.json, I get the following error.

```
Loss args OrderedDict([('normalize_vectors', False)])
Traceback (most recent call last):
  File "train.py", line 241, in <module>
    main(config, args.resume)
  File "train.py", line 169, in main
    trainer.train()
  File "/data/aschuh/source/dve/base/base_trainer.py", line 86, in train
    result = self._train_epoch(epoch)
  File "/data/aschuh/source/dve/trainer/trainer.py", line 191, in _train_epoch
    for batch_idx, batch in enumerate(self.data_loader):
  File "/data/aschuh/tools/pyenv/versions/dve/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/data/aschuh/tools/pyenv/versions/dve/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/data/aschuh/tools/pyenv/versions/dve/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/data/aschuh/tools/pyenv/versions/dve/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/data/aschuh/tools/pyenv/versions/dve/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/aschuh/tools/pyenv/versions/dve/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/aschuh/source/dve/data_loader/data_loaders.py", line 105, in __getitem__
    if (not self.use_ims and not self.use_keypoints):
AttributeError: 'CelebAPrunedAligned_MAFLVal' object has no attribute 'use_ims'
```

**Comment by albanie** [comment]
Thanks for raising this - feel free to re-open if you hit more issues.

**Comment by schuhschuh** [comment]
Thanks for looking into this so quick.
